require: rubocop-rspec

Metrics/LineLength:
  Enabled: false 

Style/AndOr:
  Enabled: false 
  
Style/SignalException: 
  EnforcedStyle: semantic

# remove fail vs raise rule
# remove || vs or  
# exclude .rake for formatting spaces 