require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Enabled: false 

Style/AndOr:
  Enabled: false 
  
Style/SignalException: 
  EnforcedStyle: semantic
  
Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Max: 30