language: ruby
rvm:
  - jruby-9.0.5.0
env:
  - DB=sqlite
script:
  - bundle exec rake db:schema:load 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec spec --trace
  
# - bundle exec rake db:test:prepare