language: ruby
rvm:
  - jruby-9.0.5.0
env:
  - DB=sqlite
script:
  - bundle exec rake setup:travis
  - bundle exec rake db:schema:load 
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/ 
  
# - bundle exec rake db:test:prepare
# - RAILS_ENV=test bundle exec rake db:migrate --trace