## For Travis CI please regenerate this file.

# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

## The secrets added to this file are accessible via Rails.application.secrets.name

development:
  secret_key_base: 7a2d473992844ca625d523d8ea86e3274aa41e4349848fb81681979e9bae8e395f8b613b7d6b65679afdbe9b4e3982529a93c485e5b133bd0481d065c812f0e4
  salt: 1
  secret_token: 2
  devise_secret_key: 00a612bc64a1262143e01dd764e0f0c7769dac1f3c0a649306a5ee65cd09abd78777d444fc79a67bd0ff38e8dc717f72fcdffe232d92bf4d596a974cf4197df0


test:
  secret_key_base: f873badf957e6bbc69ead821ca5011357e795e64cc015be7735626cf2e0aac444ad3bf43e49adafb1b80650b40a3e49f407dc6b30996da3035f845aaab5b8e91
  salt: 6

# Do not keep production secrets in the repository,
# instead read values from the environment.
# production:
#   secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
#   

production:
  secret_key_base: 945c21cbeaf89ca3dabf1be0d6b75dee95dcc3f48849e3fceeadce0f1900bd873a1489474716e6c132b7f3e7f56bf698da6dcb42bf93754b56b9f783f36c3a3b
  salt: 2
  smpt: '127.0.0.1'

## Notes:
# smpt is the ip address for smpt
# use `rake secret` to generate a secret key base code
